# Generated by Django 4.1.1 on 2022-09-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_student_f_name_alter_student_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='l_name',
            field=models.CharField(max_length=20),
        ),
    ]
