# Generated by Django 4.1.1 on 2022-09-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_doctor_subject_teachingassistant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.DeleteModel(
            name='TeachingAssistant',
        ),
    ]
