# Generated by Django 4.1.1 on 2022-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.RemoveField(
            model_name='teachingassistant',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='Menofia', max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='birthDate',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Menofia', max_length=50, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='address',
            field=models.CharField(default='Menofia', max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='birthDate',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='f_name',
            field=models.CharField(max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='l_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='f_name',
            field=models.CharField(max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='l_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthDate',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='l_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Subject Name'),
        ),
    ]
