# Generated by Django 4.1.1 on 2022-09-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_delete_product_delete_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='photos/22/09/20/img2.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
